### ISSUE TITLE
Exporter crash when server is powered off

### ISSUE THREAD

**Issue by db-wally007** [hpilo-exporter/hpilo-exporter#15]
Hello,

it seems there is an issue with exporter when server is powered off (shutdown) but iLo is still reachable.

Using:
iLo version 2.98
Exporter version: latest as of today
Python version: 3.9
OS: RHEL 9.4

The error seen in the logs:
`Exception occurred during processing of request from ('127.0.0.1', 53232)
Traceback (most recent call last):
  File "/usr/lib64/python3.9/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/tmp/tmp_container_build/hpilo-exporter/src/hpilo_exporter/exporter.py", line 109, in __init__
    BaseHTTPRequestHandler.__init__(self, request, client_address, server)
  File "/usr/lib64/python3.9/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib64/python3.9/http/server.py", line 433, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.9/http/server.py", line 421, in handle_one_request
    method()
  File "/tmp/tmp_container_build/hpilo-exporter/src/hpilo_exporter/exporter.py", line 337, in do_GET
    self.watch_memory()
  File "/tmp/tmp_container_build/hpilo-exporter/src/hpilo_exporter/exporter.py", line 142, in watch_memory
    for cpu_idx, cpu in memory_values['memory_details_summary'].items():
KeyError: 'memory_details_summary'
`

As soon as server is powered on (doesnt have to be in the OS) - the iLo exporter works fine.

**Comment by db-wally007** [comment]
fyi, I fixed it in my fork with a bit more thorough check whether memory returns any values (I guess when server is off, memory stats are empty)
